<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE car_list [
    <!--    Filename:   category_1_Tesla.xml
            Author:     Jaydon Cameron
            Validator:  https://www.xmlvalidation.com/
            Created:    03/09/2021      -->

    <!ELEMENT car_list (car+)>                      <!--Element (or tag) containing one or more car elements.-->
        <!ELEMENT car (make,model,specs,description,cost,safetyRating,extras+,couponCode?,reviews?,externalPromoPage+,promoPicFile)>  <!--Element containing information about a car.-->
            <!ELEMENT make (#PCDATA)>               <!-- Element containing the make of the car. -->
            <!ELEMENT model (#PCDATA)>              <!-- Model element with parsed character data.-->
            <!ELEMENT specs (type,range,topSpeed,zeroToHundred)>        <!-- Description element with parsed character data. -->
            <!ELEMENT description (#PCDATA)>        <!-- Description of the car. -->
            <!ELEMENT range (#PCDATA)>              <!-- Driving range of the car (in kilometers). -->
            <!ELEMENT topSpeed (#PCDATA)>           <!-- Top speed of the car (in kilometers per hour). -->
            <!ELEMENT type (#PCDATA)>               <!-- The engine/fuel type of the car. -->
            <!ELEMENT zeroToHundred (#PCDATA)>      <!-- The time it take for the car to reach 100 km/h. -->
            <!ELEMENT cost (#PCDATA)>               <!-- Cost element for the cost to purchase the car, with parsed character data. -->
            <!ELEMENT safetyRating (#PCDATA)>       <!-- safetyRating element for the safety rating of the car, with parsed character data.-->
                <!ATTLIST safetyRating stars (0|1|2|3|4|5) #REQUIRED>   <!-- The safety rating of the car according to ANCAP (out of five). -->
            <!ELEMENT extras (option, additionalCost)>                  <!-- extras element for additional options that can be chosen to add with the car purchase, containing one or more option. -->
                <!ELEMENT option (#PCDATA)>         <!-- option element with parsed character data. -->
                <!ELEMENT additionalCost (#PCDATA)> <!-- The cost to add the option to the car. -->
            <!ELEMENT couponCode (#PCDATA)>         <!-- couponCode element with parsed character data. -->
            <!ELEMENT reviews (review*)>            <!-- reviews element containing zero or more review attributes. -->
                <!ELEMENT review (#PCDATA)>         <!-- review element for a person's review of the car, with parsed character data. -->
            <!ELEMENT externalPromoPage (#PCDATA)>  <!-- URL of the cars promotional page. -->
            <!ELEMENT promoPicFile (#PCDATA)>       <!-- Image file of the cars promotional image. -->

    <!-- Entities for the car models. -->
    <!ENTITY MOD-3 "Model3">    <!-- Entity 1 -->
    <!ENTITY MOD-S "ModelS">    <!-- Entity 2 -->
    <!ENTITY MOD-X "ModelX">    <!-- Entity 3 -->
]>

<car_list>                                          <!-- List of cars. -->
    <!-- First car. -->
    <car>                                           <!-- Information for a car. -->
        <make>Tesla</make>                          <!-- Make of the car. -->
        <model>&MOD-3;</model>                      <!-- Model of the car (uses an entity). -->
        <specs>                                     <!-- List of specs of the car. -->
            <type>electric</type>                   <!-- Fuel/Engine type of the car. -->
            <range>448 km</range>                   <!-- Driving range of the car (in km) -->
            <topSpeed>225 km/h</topSpeed>           <!-- Top speed of the car (in km/h) -->
            <zeroToHundred>5.6 s</zeroToHundred>    <!-- Zero to one hundred time of the car (in s) -->
        </specs>                                    
        <description>                               <!-- Description of the car. -->
            Model 3 comes with the option of dual motor all-wheel drive, 20” Überturbine Wheels and
            Performance Brakes and lowered suspension for total control, in all weather conditions.
            And a carbon fiber spoiler improves stability at high speeds, all allowing Model 3 to
            accelerate from 0-100 km/h* in as little as 3.3 seconds.
        </description>
        <cost>59900</cost>                          <!-- Base price to purchase the car. -->
        <safetyRating stars="5"/>                   <!-- Safety rating of the car on a scale from 0 to 5 stars. -->
        <extras>                                    <!-- Extras available for the car. -->
            <option>Long Range</option>             <!-- The name of the option available. -->
            <additionalCost>13500</additionalCost>  <!-- The additional cost of the option. -->
        </extras>
        <extras>                                    <!-- Second extra. -->
            <option>Performance</option>
            <additionalCost>25000</additionalCost>
        </extras>
        <extras>                                    <!-- Third extra. -->
            <option>Standard Range Plus</option>
            <additionalCost>Included with the car.</additionalCost>
        </extras>
        <couponCode></couponCode>                   <!-- The coupon code that can be used with the purchase of this car. -->
        <reviews>                                   <!-- List of reviews of the car. -->
            <review></review>                       <!-- Review of the car. -->
        </reviews>
        <externalPromoPage>https://www.tesla.com/en_au/model3</externalPromoPage>   <!-- URL to the promotional page for this vehicle. -->
        <promoPicFile>images\tesla_model_3_white.jpg</promoPicFile>                 <!-- The relative path (or filename) of a promotional picture of this vehicle. -->
    </car>

    <!-- Second car. -->
    <car>                                           <!-- Information for a car. -->
        <make>Tesla</make>                          <!-- Make of the car. -->
        <model>&MOD-S;</model>                      <!-- Model of the car (uses an entity). -->
        <specs>                                     <!-- List of specs of the car. -->
            <type>electric</type>                   <!-- Fuel/Engine type of the car. -->
            <range>637 km (est.)</range>            <!-- Driving range of the car (in km) -->
            <topSpeed>322 km/h</topSpeed>           <!-- Top speed of the car (in km/h) -->
            <zeroToHundred>2.1 s</zeroToHundred>    <!-- Zero to one hundred time of the car (in s) -->
        </specs>
        <description>                               <!-- Description of the car. -->
            With the lowest drag coefficient on Earth and unmatched efficiency, Model S is built for speed and range.
            Together with a wider body and chassis, these elements help you go down the straight or around corners
            quicker than ever.
        </description>
        <cost>141990</cost>                         <!-- Base price to purchase the car. -->
        <safetyRating stars="5"/>                   <!-- Safety rating of the car on a scale from 0 to 5 stars. -->
        <extras>                                    <!-- Extras available for the car. -->
            <option>Long Range</option>             <!-- The name of the option available. -->
            <additionalCost>Included with the car.</additionalCost> <!-- The additional cost of the option. -->
        </extras>
        <extras>                                    <!-- Second extra. -->
            <option>Plaid</option>
            <additionalCost>45000</additionalCost>
        </extras>
        <couponCode></couponCode>                   <!-- The coupon code that can be used with the purchase of this car. -->
        <reviews>                                   <!-- List of reviews of the car. -->
            <review></review>                       <!-- Review of the car. -->
        </reviews>
        <externalPromoPage>https://www.tesla.com/en_au/models</externalPromoPage>   <!-- URL to the promotional page for this vehicle. -->
        <promoPicFile>images\ms-main-hero-desktop.jpg</promoPicFile>                <!-- The relative path (or filename) of a promotional picture of this vehicle. -->
    </car>

    <!-- Third car. -->
    <car>                                           <!-- Information for a car. -->
        <make>Tesla</make>                          <!-- Make of the car. -->
        <model>&MOD-X;</model>                      <!-- Model of the car (uses an entity). -->
        <specs>                                     <!-- List of specs of the car. -->
            <type>electric</type>                   <!-- Fuel/Engine type of the car. -->
            <range>547 km (est.)</range>            <!-- Driving range of the car (in km) -->
            <topSpeed>262 km/h</topSpeed>           <!-- Top speed of the car (in km/h) -->
            <zeroToHundred>2.6 s</zeroToHundred>    <!-- Zero to one hundred time of the car (in s) -->
        </specs>
        <description>                               <!-- Description of the car. -->
            With the most storage space and towing capacity of any electric SUV, and seating for up to
            seven adults, Model X delivers maximum utility. Front doors open and close automatically,
            Falcon Wing doors allow for easier loading and a standard trailer hitch lets you bring your
            gear anywhere you go.
        </description>
        <cost>161990</cost>                         <!-- Base price to purchase the car. -->
        <safetyRating stars="5"/>                   <!-- Safety rating of the car on a scale from 0 to 5 stars. -->
        <extras>                                    <!-- Extras available for the car. -->
            <option>Long Range</option>             <!-- The name of the option available. -->
            <additionalCost>Included with the car.</additionalCost> <!-- The additional cost of the option. -->
        </extras>
        <extras>                                    <!-- Second extra. -->
            <option>Plaid</option>
            <additionalCost>13000</additionalCost>
        </extras>
        <couponCode></couponCode>                   <!-- The coupon code that can be used with the purchase of this car. -->
        <reviews>                                   <!-- List of reviews of the car. -->
            <review></review>                       <!-- Review of the car. -->
        </reviews>
        <externalPromoPage>https://www.tesla.com/en_au/modelx</externalPromoPage>   <!-- URL to the promotional page for this vehicle. -->
        <promoPicFile>images\MX-Hero-Desktop.jpg</promoPicFile>                     <!-- The relative path (or filename) of a promotional picture of this vehicle. -->
    </car>
</car_list>